name: Send Buffett Excel at 8AM KST

on:
  schedule:
    - cron: '0 23 * * 1,5'  # 매주 월~금 23:00 UTC = KST 08:00 (다음날 5PM)
  workflow_dispatch:

jobs:
  send-daily-excel:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Buffett script and email
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          MARKETAUX_API: ${{ secrets.MARKETAUX_API }}
        run: python src/buffett_us.py

  update-cache:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && startsWith(github.event.schedule, '0 23 * * 6'))

    steps:
      - name: Checkout repo with write access
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install -r requirements2.txt

      - name: Run cache update script
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        run: python src/yf_cache_downloader.py

      - name: Commit and push updated cache
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 1. 변경사항 먼저 커밋
          git add yf_cache_multi.csv
          git commit -m "Update cache file at $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

          # 2. 원격 fetch 후 rebase
          git fetch origin main
          git rebase origin/main || echo "Rebase failed"

          # 3. 푸시
          git push origin main
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub Actions가 자동으로 제공하는 토큰


