name: Send Buffett Report at 8 AM KST

on:
  schedule:
    - cron: '0 23 * * 1-5'  # 매주 월~금 23:00 UTC → KST 기준 08:00 다음날 (즉, 한국시간 오후 5시)
  workflow_dispatch:  # 수동 실행 허용

jobs:
  send-daily-excel:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Buffett script and email
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        run: python src/buffett_us.py

  update-cache:
    runs-on: ubuntu-latest
    # 자동 실행: 토요일 08:00 KST (즉 금요일 23:00 UTC)만 실행 또는 수동 실행 시에도 허용
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && startsWith(github.event.schedule, '0 23 * * 6'))

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run cache update script
        run: python src/yf_cache_downloader.py
